In [ ]:
import torch as t
from torch import nn

In [ ]:
class Encoder(nn.Module):
    def __init__(self, src_vocab_size, embed_size, hidden_size, n_layers=1, dropout=0.5):
        super().__init__()
        self.input_vocab_size = src_vocab_size
        self.embed_size = embed_size
        self.hidden_size = hidden_size
        self.embed = nn.Embedding(src_vocab_size, embed_size, padding_idx)
        self.lstm = nn.LSTM(embed_size, hidden_size, n_layers, dropout=dropout, bidirectional=True)

    def forward(self, src, hidden=None):
        embedded = self.embed(src)
        outputs, hidden = self.lstm(src)
        return outpurs, hidden

In [ ]:
class Attention(nn.Moudle):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear()

    def forward(self, hidden, encoder_outputs):
        

In [ ]:
class Decoder(nn.Moudle):
    def __init(self, tgt_vocab_size, embed_size, hidden_size, n_layers=1, dropout=0.5):
        super().__init__()
        self.embed = nn.Embedding(tgt_vocab_size, embed_size, padding_idx)
        self.attention = Attention(hidden_size)
        self.lstm = nn.LSTM(embed_size, hidden_size, n_layers, dropout)
        self.linear = nn.Linear(hidden_size*2, tgt_vocab_size)

In [ ]:
class Seq2Seq(nn.Moudle):
    def __init__(self, ):
        super().__init__()
        self.enc=Encoder()
        self.dec=Decoder()

In [109]:
lstm= nn.LSTM(3,4)
gru = nn.GRU(3,5,1)

In [110]:
a = t.Tensor([[[3,4,5]],[[1,2,3]],[[4,5,6]]])

In [111]:
a.shape

torch.Size([3, 1, 3])

In [112]:
o,h = lstm(a)

In [113]:
o

tensor([[[ 0.0133, -0.0772, -0.1376,  0.1783]],

        [[ 0.0974, -0.1345, -0.3137,  0.2529]],

        [[ 0.0368, -0.0761, -0.1067,  0.1547]]], grad_fn=<StackBackward>)

In [114]:
h

(tensor([[[ 0.0368, -0.0761, -0.1067,  0.1547]]], grad_fn=<StackBackward>),
 tensor([[[ 0.1029, -0.1217, -0.1677,  0.9221]]], grad_fn=<StackBackward>))

In [115]:
gru(a)

(tensor([[[ 0.4122, -0.4796,  0.7884,  0.8438, -0.6294]],
 
         [[ 0.4351, -0.7290,  0.8668,  0.8095, -0.6690]],
 
         [[ 0.6093, -0.8994,  0.9607,  0.9502, -0.8861]]],
        grad_fn=<StackBackward>),
 tensor([[[ 0.6093, -0.8994,  0.9607,  0.9502, -0.8861]]],
        grad_fn=<StackBackward>))